on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-test-publish:
    name: 'Build, Test and Publish'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 15.6

      - name: 'Install Dependencies'
        run: yarn

      - name: 'Test'
        run: yarn test

      - name: 'Build'
        run: yarn build

      - name: 'Publish to NPM'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          npm config delete //registry.npmjs.org/:_authToken
