on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  NODE_VERSION: ''

jobs:
  build-test-publish:
    name: 'Main Pipeline'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Determine Node version'
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: 'Setup Node'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Test'
        run: npm run test

      - name: 'Build'
        run: npm run build

      - name: 'Publish to NPM'
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm publish --access public
          npm config delete //registry.npmjs.org/:_authToken
